services:
  # mongodb:
  #   image: "mongo"
  #   volumes:
  #     - data:/data/db
  #   environment:
  #     - TZ=Asia/Seoul  
  wetube-practice:
    build: ./
    ports:
      - "4000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env  
    environment:
      - TZ=Asia/Seoul      
    # depends_on:
    #   - mongodb
volumes:
  data: